### ISSUE TITLE
Reports on code coverage

### ISSUE THREAD

**Issue by skywarth** [nyingi/Rocket.Libraries.Validation#1]
Do you have any publicly available code coverage reports ? Or when do you plan to do unit tests ? 
By the way, project seems interesting. Reserved by star to check again later. Keep up the good work.

**Comment by nyingi** [comment]
> Do you have any publicly available code coverage reports ? Or when do you plan to do unit tests ?
> By the way, project seems interesting. Reserved by star to check again later. Keep up the good work.

At the moment I've done really basic unit testing but plan to up my coverage in the next two weeks. I'll definitely generate coverage reports and share as well as more explicitly highlight the unit tests

**Comment by skywarth** [comment]
Good to know, looking forward to it. Thanks.
